[pytest]
# 配置命令行初始参数
# --alluredir 指定报告数据存放位置
# --clean-alluredir 每次运行前清空旧的报告数据
addopts = -vs --alluredir=./report/allure-results --clean-alluredir

# 搜索用例的范围
testpaths = ./testcases

# 规定测试模块、类、函数的命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 配置日志（让控制台输出更清晰）
log_cli = false
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

